services:
  frontend:
    image: phenix-studio-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MODE: ${NEXT_PUBLIC_MODE:-DEV}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-}
        NEXT_PUBLIC_ECOSYSTEM_FRONT_END_URL: ${NEXT_PUBLIC_ECOSYSTEM_FRONT_END_URL:-}
        NEXT_PUBLIC_PLATFORM_NAME: ${NEXT_PUBLIC_PLATFORM_NAME:-}
        NEXT_PUBLIC_ACTIVE_THEME: ${NEXT_PUBLIC_ACTIVE_THEME:-}
        NEXT_PUBLIC_APP_TITLE: ${NEXT_PUBLIC_APP_TITLE:-}
        NEXT_PUBLIC_FOOTER_TEXT: ${NEXT_PUBLIC_FOOTER_TEXT:-}
        NEXT_PUBLIC_LOGO_BASE_URL: ${NEXT_PUBLIC_LOGO_BASE_URL:-}
        NEXT_PUBLIC_CURRENT_RELEASE: ${NEXT_PUBLIC_CURRENT_RELEASE:-}
        NEXT_PUBLIC_ENABLE_APP_LAUNCHER: ${NEXT_PUBLIC_ENABLE_APP_LAUNCHER:-false}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-}
        NEXT_PUBLIC_ENABLE_SOCIAL_LOGIN: ${NEXT_PUBLIC_ENABLE_SOCIAL_LOGIN:-false}
        NEXT_PUBLIC_ENABLE_BILLING_OPTION: ${NEXT_PUBLIC_ENABLE_BILLING_OPTION:-false}
        NEXT_PUBLIC_SOVIO_LANDINGPAGE_URL: ${NEXT_PUBLIC_SOVIO_LANDINGPAGE_URL:-}
        NEXT_PUBLIC_LANDINGPAGE_URL: ${NEXT_PUBLIC_LANDINGPAGE_URL:-}
        NEXT_PUBLIC_POLYGON_TESTNET_URL: ${NEXT_PUBLIC_POLYGON_TESTNET_URL:-}
        NEXT_PUBLIC_POLYGON_MAINNET_URL: ${NEXT_PUBLIC_POLYGON_MAINNET_URL:-}
        NEXT_PUBLIC_MARKETPLACE_MANAGE_URL: ${NEXT_PUBLIC_MARKETPLACE_MANAGE_URL:-}
        NEXT_PUBLIC_MARKETPLACE_PRODUCT_NAME: ${NEXT_PUBLIC_MARKETPLACE_PRODUCT_NAME:-}
        NEXT_PUBLIC_MARKETPLACE_PUBLISHER_NAME: ${NEXT_PUBLIC_MARKETPLACE_PUBLISHER_NAME:-}
        NEXT_PUBLIC_MARKETPLACE_SUPPORT_EMAIL: ${NEXT_PUBLIC_MARKETPLACE_SUPPORT_EMAIL:-}
        NEXT_PUBLIC_MARKETPLACE_PRIVACY_EMAIL: ${NEXT_PUBLIC_MARKETPLACE_PRIVACY_EMAIL:-}
        NEXT_PUBLIC_ADMIN_PORTAL_CLIENT_ID: ${NEXT_PUBLIC_ADMIN_PORTAL_CLIENT_ID:-}
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: ${CONTAINER_PORT:-3000}
    ports:
      - "${HOST_PORT:-3000}:${CONTAINER_PORT:-3000}"
    command: ["npm", "start", "--", "-p", "${CONTAINER_PORT:-3000}"]
    restart: unless-stopped
